cbvapp/urls.py
from django.urls import path
from cbvapp import views

app_name='cbvapp'

urlpatterns =[
    
    path('',views.SchoolListView.as_view(),name='list'),
    path('<int:pk>',views.SchoolDetails.as_view(),name='detail'),
    path('create/',views.SchoolCreateView.as_view(),name='create'),
    path('update/<int:pk>',views.SchoolUpdate.as_view(),name='update'),
    path('delete/<int:pk>',views.SchoolDelete.as_view(),name='delete'),

]

cbvproject/urls.py
from django.contrib import admin
from django.urls import path,include
from cbvapp import views

urlpatterns = [
    path('',views.index_view.as_view(),name='index'),
    path('cbvapp/',include('cbvapp.urls')),
    path('admin/', admin.site.urls),
]

cbvapp/models.py
from django.db import models
from django.urls import reverse



# Create your models here.
class School(models.Model):
    name = models.CharField(max_length=100)
    principal = models.CharField(max_length=100)
    place = models.CharField(max_length=100)
    english='EG'
    kannada='KA'
    hindhi='HI'
    MEDIUM=[
        (english,'english'),
        (kannada,'kannada'),
        (hindhi,'hindi'),
    ]
    medium = models.CharField(max_length=100,default='English',choices=MEDIUM)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse("cbvapp:detail",kwargs={"pk":self.pk})
       
class Student(models.Model):
    std_name = models.CharField(max_length=100) 
    age = models.IntegerField()  
    marks = models.IntegerField()
    address = models.CharField(max_length=200) 
    school = models.ForeignKey(School,related_name='school',on_delete=models.CASCADE)
    
    
    def __str__(self):
        return self.std_name
    
 

cbvapp/views.py
from django.shortcuts import render
from django.views.generic import View,TemplateView,ListView,DetailView,CreateView,UpdateView,DeleteView
from django.http import HttpResponse
from cbvapp.models import School

# Create your views here.

# class myclass(view):
#     def get(self,request):
#         return HttpResponse('thise is class')


class index_view(TemplateView):
    template_name = 'index.html'

class SchoolListView(ListView)  :
    context_object_name = 'myschools'
    model = School

class SchoolDetails(DetailView)  :
    context_object_name = 'school_details'  
    model = School
    template_name = 'cbvapp/school_details.html'

class SchoolCreateView(CreateView):
    fields = ['name','principal','place']
    model = School

class SchoolUpdate(UpdateView):
    fields = ['principal','place']
    model = School

class SchoolDelete(DeleteView)   :
    model = School 

    

cbvapp/templates/cbvapp/school_conform_delete.html
{% extends 'base.html' %}

{% block content %}
<h2>do you want to delete...!</h2>

{% endblock %}  

cbvapp/templates/cbvapp/school_details.html
{% extends 'base.html' %}

{% block content %}
    <div class="card">
        <h1 class="card-header">{{ school_details.name }} </h1>
        <div class="card-body">
            <h5 class="card-title">School details</h5>
            <p class="card-text">School Name : {{ school_details.name }}</p>
            <p class="card-text">Principal : {{ school_details.principal }}</p>
            <p class="card-text">Place : {{ school_details.place }}</p>
           
            <a class="btn btn-warning" href="{% url 'cbvapp:update' pk=school_details.pk %}">Update</a>
            <a class="btn btn-danger" href="{% url 'cbvapp:delete' pk=school_details.pk %}">Delete</a>
            <hr>
            <h4>List of Students</h4>
            {% for std in school_details.school.all %}
                <p>{{ std.std_name }} Whose age is {{ std.age }} and scored a marks {{ std.marks }}</p>
            {% endfor %}


        </div>
    </div>

{% endblock %}

cbvapp/templates/cbvapp/school_form.html
{% extends 'base.html' %} 

{% block content %}

    <div class="jumbotron">
        {% if not form.instance.pk %}
            <h1>add new school</h1>
            <form action="" method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" value="create">
            </form>
        {% else %}    
            <h1>update school</h1>
            <form action="" method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" value="create">
            </form>
        {% endif %}    
    </div>


 {% endblock %}  
    

cbvapp/templates/cbvapp/school_list.html
{% extends 'base.html' %}

{% block content %}
    <h1>
        list of student
    </h1>
    <hr>
    <ol>
        {% for school in myschools %}
            <li><a href="{{school.id}}">{{ school }}</a></li>
        {% endfor %}

{% endblock %}     

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
    
</head>
<body>
    <nav class="navbar navbar-dark bg-dark">
        <div class="container">
            <ul class="nav navbar">
                <li class="nav item">
                    <a href="{% url 'index' %}" class="nav-link">HOME</a>
                </li>
                <li class="nav item">
                    <a href="{% url 'admin:index' %}" class="nav-link">ADMIN</a>
                </li>
                <li class="nav item">
                    <a href="{% url 'cbvapp:create' %}" class="nav-link">ADD-SCHOOL</a>
                </li>
            </ul>
        </div>
        
    </nav>     
    
    {% block content %}

    {% endblock %}
</body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block content %}
<div class="jumbotron">
    <h2>This is a class</h2>
</div>


{% endblock %}  